# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: model-prop-apply-prospects

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource: '*'
          
# you can add packaging information here
package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - node_modules/**
    - .gitignore
    - .ipynb_checkpoints/**
    - __pycache__/**
    - deploy.sh

functions:
  predict-apply:
    image:
      name: appimage
    #handler: handler.lambda_handler # Alteração para o nome definido no handler.py
    memorySize: 3008
    timeout: 30
    events:
      - http:
          path: get-predict
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                jobId: true
                linkedinUsername: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true