# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aula-deploy-modelo

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - glue:*
            - athena:*
            - dynamodb:*
            - s3:*
          Resource: '*'
          
# you can add packaging information here
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .ipynb_checkpoints/**
    - __pycache__/**
    - deploy.sh

functions:
  predict-survive:
    image:
      name: appimage    
    memorySize: 3008
    timeout: 30
    events:
      - http:
          path: get-predict
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                passenger_id: true
                embarked: true
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true