service: recommendation-svc
frameworkVersion: ">=2.24.0"
provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1  
functions:
  random-recommendation:
    handler: handler.lambda_handler
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: get-recommendation
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                user_id: true
plugins:
  - serverless-python-requirements